"""add_notes_field_to_webinar_registrants

Revision ID: 0333e16b1b9d
Revises: 714ef079d138
Create Date: 2025-08-05 10:03:28.310459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0333e16b1b9d'
down_revision: Union[str, Sequence[str], None] = '714ef079d138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
